id: P424ADC12
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG5846
  instance_id: http://purl.bdrc.io/resource/IE1KG5846
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རིག་འཛིན་འཇིགས་མེད་ནུས་ལྡན་རྡོ་རྗེ་རྩལ་གྱི་མ་འོངས་ལུང་བསྟན།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1KG5847
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    94c5e3631455495ea51afdf4cc478bab:
      title: པོད ༡་རིག་འཛིན་འཇིགས་མེད་ནུས་ལྡན་རྡོ་རྗེ་རྩལ་གྱི་མ་འོངས་ལུང་བསྟན།
      volume_number: 1
      base_file: UT1KG5846_I1KG5856_0000.txt
      reference: http://purl.bdrc.io/resource/VL662C9B8F7DDD5413
      image_group: I1KG5856
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG5846
  - http://purl.bdrc.io/resource/MW1KG5846
  ocr_software: Namsel
created_at: '2021-12-22T10:52:54.789366'
last_modified_at: '2021-12-22T10:52:54.789372'
